Repository stolostron/ocm, pull requests merged in 2025-06, with the labels that each got.

#399 :seedling: Change tekton target branch to backplane-2.9.
  .tekton/addon-manager-mce-29-pull-request.yaml
  .tekton/addon-manager-mce-29-push.yaml
  .tekton/placement-mce-29-pull-request.yaml
  .tekton/placement-mce-29-push.yaml
  .tekton/registration-mce-29-pull-request.yaml
  .tekton/registration-mce-29-push.yaml
  .tekton/registration-operator-mce-29-pull-request.yaml
  .tekton/registration-operator-mce-29-push.yaml
  .tekton/work-mce-29-pull-request.yaml
  .tekton/work-mce-29-push.yaml
Labels: approved

#402 :seedling: Upgrade rpms-signature-scan.
  .tekton/addon-manager-mce-29-pull-request.yaml
  .tekton/addon-manager-mce-29-push.yaml
  .tekton/placement-mce-29-pull-request.yaml
  .tekton/placement-mce-29-push.yaml
  .tekton/registration-mce-29-pull-request.yaml
  .tekton/registration-mce-29-push.yaml
  .tekton/registration-operator-mce-29-pull-request.yaml
  .tekton/registration-operator-mce-29-push.yaml
  .tekton/work-mce-29-pull-request.yaml
  .tekton/work-mce-29-push.yaml
Labels: approved

#392 🐛 watch filtered configmaps & deployments to reduce memory usage of c…
  manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
  pkg/operator/helpers/helpers.go
  pkg/operator/helpers/helpers_test.go
  pkg/operator/helpers/queuekey.go
  pkg/operator/operators/clustermanager/options.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
  test/integration/operator/klusterlet_aws_test.go
  test/integration/operator/klusterlet_test.go
Labels: lgtm, approved

#401 :seedling: Upgrade rpms signature scan[MCE 2.9]
  .tekton/addon-manager-mce-29-pull-request.yaml
  .tekton/addon-manager-mce-29-push.yaml
  .tekton/placement-mce-29-pull-request.yaml
  .tekton/placement-mce-29-push.yaml
  .tekton/registration-mce-29-pull-request.yaml
  .tekton/registration-mce-29-push.yaml
  .tekton/registration-operator-mce-29-pull-request.yaml
  .tekton/registration-operator-mce-29-push.yaml
  .tekton/work-mce-29-pull-request.yaml
  .tekton/work-mce-29-push.yaml
Labels: lgtm, approved, ok-to-test

#400 🐛 watch filtered configmaps & deployments to reduce memory usage of c…
  manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
  pkg/operator/helpers/helpers.go
  pkg/operator/helpers/helpers_test.go
  pkg/operator/helpers/queuekey.go
  pkg/operator/operators/clustermanager/options.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
  test/integration/operator/klusterlet_test.go
Labels: lgtm, approved

#398 🐛 watch filtered configmaps & deployments to reduce memory usage of c…
  manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
  manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
  pkg/operator/helpers/helpers.go
  pkg/operator/helpers/helpers_test.go
  pkg/operator/helpers/queuekey.go
  pkg/operator/operators/clustermanager/options.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
  pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
  test/integration/operator/klusterlet_aws_test.go
  test/integration/operator/klusterlet_test.go
Labels: lgtm, approved

#423 hardcode CI version to unblock konflux build
  build/Dockerfile.registration-operator.rhtap
Labels: lgtm, approved

#425 [mce-2.9] update konflux images
  .tekton/addon-manager-mce-29-pull-request.yaml
  .tekton/addon-manager-mce-29-push.yaml
  .tekton/placement-mce-29-pull-request.yaml
  .tekton/placement-mce-29-push.yaml
  .tekton/registration-mce-29-pull-request.yaml
  .tekton/registration-mce-29-push.yaml
  .tekton/registration-operator-mce-29-pull-request.yaml
  .tekton/registration-operator-mce-29-push.yaml
  .tekton/work-mce-29-pull-request.yaml
  .tekton/work-mce-29-push.yaml
Labels: lgtm, approved
